/* This file was generated by the Hex-Rays decompiler version 9.0.0.240807.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// __int64 _gmon_start__(void); weak
// int puts(const char *s);
// void operator delete(void *); idb
// void __noreturn exit(int status);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int putchar(int c);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int system(const char *command);
// char *fgets(char *s, int n, FILE *stream);
// int scanf(const char *format, ...);
// void free(void *ptr);
// int _cxa_finalize(void *);
// char *strchr(const char *s, int c);
// unsigned int alarm(unsigned int seconds);
// char *strdup(const char *s);
// int rand(void);
// _QWORD operator new(unsigned __int64); idb
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
__int64 (**sub_F70())(void);
__int64 sub_FB0(void); // weak
__int64 (**sub_1000())(void);
__int64 sub_1040(); // weak
__int64 __fastcall sub_1070(_QWORD *a1);
__int64 __fastcall sub_10D8(_QWORD *a1);
void __fastcall sub_1116(_QWORD *a1);
__int64 __fastcall sub_113C(__int64 a1, __int64 a2);
void *__fastcall sub_116E(_QWORD *a1);
__int64 __fastcall sub_11E4(_QWORD *a1);
void __fastcall sub_1222(_QWORD *a1);
int __fastcall sub_1248(__int64 a1, char a2);
__int64 __fastcall sub_12C0(__int64 a1, unsigned int a2);
void *__fastcall sub_1308(_QWORD *a1);
__int64 __fastcall sub_137E(_QWORD *a1);
void __fastcall sub_13BC(_QWORD *a1);
__int64 __fastcall sub_13E2(__int64 a1, unsigned __int8 *a2);
int __fastcall sub_1424(__int64 a1, char a2);
__int64 __fastcall sub_149C(__int64 a1, unsigned int a2);
char __fastcall sub_14E3(__int64 a1, unsigned __int8 *a2);
int __fastcall sub_151F(__int64 a1);
int __fastcall sub_1583(const char *a1);
int __fastcall sub_159D(const char *a1);
__int64 __fastcall sub_15C3(__int64 a1);
int sub_1604();
__int64 sub_1669(void); // weak
__int64 sub_16AD();
unsigned __int64 sub_1729();
int sub_18C0();
int sub_195C();
int sub_19DA();
unsigned __int64 sub_1A3E();
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3);
__int64 __fastcall sub_1D36(__int64 a1);
__int64 __fastcall sub_1D6C(__int64 a1);
void __fastcall sub_1DBA(void *a1);
__int64 __fastcall sub_1DE0(__int64 a1, char a2);
__int64 __fastcall sub_1DFA(__int64 a1);
void __fastcall sub_1E10(__int64 a1, const char *a2);
__int64 __fastcall sub_1E5E(__int64 a1);
__int64 __fastcall sub_1E70(__int64 a1, __int16 a2);
__int64 __fastcall sub_1E9A(__int64 a1);
__int64 __fastcall sub_1EE8(__int64 a1);
int __fastcall sub_1EFE(__int64 a1, char a2);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void fini(void); // idb
void term_proc();
// int __cxa_finalize(void *);
// __int64 Jv_RegisterClasses(void); weak
// __int64 ITM_deregisterTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_202C48[2])() = { &sub_1040, &sub_1000 }; // weak
__int64 (__fastcall *off_202C50)() = &sub_1000; // weak
_UNKNOWN unk_202C58; // weak
__int64 (__fastcall *off_202C70[2])() = { &sub_10D8, &sub_1116 }; // weak
__int64 (__fastcall *off_202C90[2])() = { &sub_11E4, &sub_1222 }; // weak
__int64 (__fastcall *off_202CB0[2])() = { &sub_137E, &sub_13BC }; // weak
__int64 (__fastcall *off_202CD0[2])() = { &sub_1D6C, &sub_1DBA }; // weak
void *off_203008 = &off_203008; // idb
_UNKNOWN *off_203020 = &unk_22D4; // weak
FILE *_bss_start; // idb
FILE *stderr; // idb
FILE *stdout; // idb
char byte_203070; // weak
_QWORD qword_203080[10]; // weak
int dword_2030D0; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (0000000000000E58) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    return (void *)_gmon_start__();
  return result;
}
// EA0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000000F40) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(main, v4, &retaddr, init, fini, a3, &v5);
  __halt();
}
// F46: positive sp value 8 has been found
// F4D: variable 'v3' is possibly undefined

//----- (0000000000000F70) ----------------------------------------------------
__int64 (**sub_F70())(void)
{
  __int64 (**result)(void); // rax

  result = (__int64 (**)(void))((char *)&_bss_start + 7 - (char *)&_bss_start);
  if ( (unsigned __int64)((char *)&_bss_start + 7 - (char *)&_bss_start) > 0xE )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      return (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return result;
}
// 2031A8: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000000FB0) ----------------------------------------------------
__int64 sub_FB0()
{
  return 0LL;
}
// FB0: using guessed type __int64 sub_FB0();

//----- (0000000000001000) ----------------------------------------------------
__int64 (**sub_1000())(void)
{
  __int64 (**result)(void); // rax

  if ( !byte_203070 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_203008);
    result = sub_F70();
    byte_203070 = 1;
  }
  return result;
}
// 203070: using guessed type char byte_203070;

//----- (0000000000001040) ----------------------------------------------------
__int64 sub_1040()
{
  if ( unk_202C58 && &Jv_RegisterClasses )
    Jv_RegisterClasses();
  return sub_FB0();
}
// FB0: using guessed type __int64 sub_FB0(void);
// 1040: using guessed type __int64 sub_1040();
// 2031A0: using guessed type __int64 Jv_RegisterClasses(void);

//----- (0000000000001070) ----------------------------------------------------
__int64 __fastcall sub_1070(_QWORD *a1)
{
  sub_1D36((__int64)a1);
  *a1 = off_202C70;
  a1[3] = 0LL;
  return sub_1DE0((__int64)a1, 3);
}
// 202C70: using guessed type __int64 (__fastcall *off_202C70[2])();

//----- (00000000000010D8) ----------------------------------------------------
__int64 __fastcall sub_10D8(_QWORD *a1)
{
  *a1 = off_202C70;
  sub_1D6C((__int64)a1);
  return 0LL;
}
// 202C70: using guessed type __int64 (__fastcall *off_202C70[2])();

//----- (0000000000001116) ----------------------------------------------------
void __fastcall sub_1116(_QWORD *a1)
{
  sub_10D8(a1);
  operator delete(a1);
}

//----- (000000000000113C) ----------------------------------------------------
__int64 __fastcall sub_113C(__int64 a1, __int64 a2)
{
  __int64 result; // rax

  result = *(_QWORD *)(a1 + 24);
  if ( result )
    return (*(__int64 (__fastcall **)(__int64))(a1 + 24))(a2);
  return result;
}

//----- (000000000000116E) ----------------------------------------------------
void *__fastcall sub_116E(_QWORD *a1)
{
  sub_1D36((__int64)a1);
  *a1 = off_202C90;
  sub_1DE0((__int64)a1, 2);
  return memset((char *)a1 + 18, 0, 0xAuLL);
}
// 202C90: using guessed type __int64 (__fastcall *off_202C90[2])();

//----- (00000000000011E4) ----------------------------------------------------
__int64 __fastcall sub_11E4(_QWORD *a1)
{
  *a1 = off_202C90;
  sub_1D6C((__int64)a1);
  return 0LL;
}
// 202C90: using guessed type __int64 (__fastcall *off_202C90[2])();

//----- (0000000000001222) ----------------------------------------------------
void __fastcall sub_1222(_QWORD *a1)
{
  sub_11E4(a1);
  operator delete(a1);
}

//----- (0000000000001248) ----------------------------------------------------
int __fastcall sub_1248(__int64 a1, char a2)
{
  if ( a2 )
    puts("Type\tName\t\tCups\tColor");
  return printf(
           "%s\t%s\t\t%d\t%s\n",
           (const char *)*(&off_203020 + *(char *)(a1 + 9)),
           *(const char **)(a1 + 10),
           *(unsigned __int8 *)(a1 + 8),
           (const char *)(a1 + 18));
}
// 203020: using guessed type _UNKNOWN *off_203020;

//----- (00000000000012C0) ----------------------------------------------------
__int64 __fastcall sub_12C0(__int64 a1, unsigned int a2)
{
  __int64 result; // rax

  result = a2;
  if ( a2 == 1 )
  {
    result = a1 + 18;
    strcpy((char *)(a1 + 18), "black");
  }
  else if ( a2 == 2 )
  {
    result = a1 + 18;
    strcpy((char *)(a1 + 18), "white");
  }
  return result;
}

//----- (0000000000001308) ----------------------------------------------------
void *__fastcall sub_1308(_QWORD *a1)
{
  sub_1D36((__int64)a1);
  *a1 = off_202CB0;
  sub_1DE0((__int64)a1, 1);
  return memset((char *)a1 + 18, 0, 0xAuLL);
}
// 202CB0: using guessed type __int64 (__fastcall *off_202CB0[2])();

//----- (000000000000137E) ----------------------------------------------------
__int64 __fastcall sub_137E(_QWORD *a1)
{
  *a1 = off_202CB0;
  sub_1D6C((__int64)a1);
  return 0LL;
}
// 202CB0: using guessed type __int64 (__fastcall *off_202CB0[2])();

//----- (00000000000013BC) ----------------------------------------------------
void __fastcall sub_13BC(_QWORD *a1)
{
  sub_137E(a1);
  operator delete(a1);
}

//----- (00000000000013E2) ----------------------------------------------------
__int64 __fastcall sub_13E2(__int64 a1, unsigned __int8 *a2)
{
  __int64 result; // rax
  _BYTE *v3; // rax
  _BYTE *i; // [rsp+18h] [rbp-8h]

  for ( i = (_BYTE *)(a1 + 18); ; ++i )
  {
    result = *a2;
    if ( !(_BYTE)result )
      break;
    v3 = i;
    *v3 = *a2++;
  }
  return result;
}

//----- (0000000000001424) ----------------------------------------------------
int __fastcall sub_1424(__int64 a1, char a2)
{
  if ( a2 )
    puts("Type\tName\t\tCups\tColor");
  return printf(
           "%s\t%s\t\t%d\t%s\n",
           (const char *)*(&off_203020 + *(char *)(a1 + 9)),
           *(const char **)(a1 + 10),
           *(unsigned __int8 *)(a1 + 8),
           (const char *)(a1 + 18));
}
// 203020: using guessed type _UNKNOWN *off_203020;

//----- (000000000000149C) ----------------------------------------------------
__int64 __fastcall sub_149C(__int64 a1, unsigned int a2)
{
  __int64 result; // rax

  result = a2;
  if ( a2 )
  {
    if ( a2 == 1 )
    {
      result = a1 + 18;
      strcpy((char *)(a1 + 18), "white");
    }
  }
  else
  {
    result = a1 + 18;
    strcpy((char *)(a1 + 18), "black");
  }
  return result;
}

//----- (00000000000014E3) ----------------------------------------------------
char __fastcall sub_14E3(__int64 a1, unsigned __int8 *a2)
{
  char result; // al

  result = (unsigned int)sub_1DFA(a1) == 1;
  if ( result )
    return sub_13E2(a1, a2);
  return result;
}

//----- (000000000000151F) ----------------------------------------------------
int __fastcall sub_151F(__int64 a1)
{
  int result; // eax

  result = sub_1DFA(a1);
  switch ( result )
  {
    case 2:
      return sub_1248(a1, 0);
    case 3:
      return sub_1EFE(a1, 0);
    case 1:
      return sub_1424(a1, 0);
  }
  return result;
}

//----- (0000000000001583) ----------------------------------------------------
int __fastcall sub_1583(const char *a1)
{
  return system(a1);
}

//----- (000000000000159D) ----------------------------------------------------
int __fastcall sub_159D(const char *a1)
{
  return printf("Fish is deep-diving at %s\n", a1);
}

//----- (00000000000015C3) ----------------------------------------------------
__int64 __fastcall sub_15C3(__int64 a1)
{
  __int64 result; // rax

  result = sub_1DFA(a1);
  if ( (_DWORD)result == 3 )
  {
    result = a1;
    *(_QWORD *)(a1 + 24) = sub_159D;
  }
  return result;
}

//----- (0000000000001604) ----------------------------------------------------
int sub_1604()
{
  setvbuf(stdout, 0LL, 2, 0LL);
  setvbuf(stderr, 0LL, 2, 0LL);
  alarm(0x1F4u);
  puts("HackerShop");
  return puts("Your neighborhood pet shop: healthy pets, expert grooming and quality supplies - now open!");
}

//----- (0000000000001669) ----------------------------------------------------
__int64 sub_1669()
{
  unsigned int v1; // [rsp+Ch] [rbp-4h] BYREF

  if ( scanf("%d%*c", &v1) <= 0 )
  {
    puts("invalid number");
    exit(0);
  }
  return v1;
}
// 1669: using guessed type __int64 sub_1669();

//----- (00000000000016AD) ----------------------------------------------------
__int64 sub_16AD()
{
  puts("=====================");
  puts("== PetShop ==");
  puts("1. Buy a pet");
  puts("2. Feed");
  puts("3. Poop");
  puts("4. Show");
  puts("5. Play");
  puts("6. Exit");
  printf("Your choice: ");
  return sub_1669();
}
// 1669: using guessed type __int64 sub_1669(void);

//----- (0000000000001729) ----------------------------------------------------
unsigned __int64 sub_1729()
{
  _QWORD *v0; // rbx
  unsigned int v1; // eax
  unsigned int v2; // eax
  char *v4; // [rsp+18h] [rbp-128h]
  char s[264]; // [rsp+20h] [rbp-120h] BYREF
  unsigned __int64 v6; // [rsp+128h] [rbp-18h]

  v6 = __readfsqword(0x28u);
  if ( dword_2030D0 == 10 )
    puts("You can not buy anything.");
  puts("Choose animal:\n\t1. Dog\n\t2. Cat\n\t3. Fish");
  if ( (unsigned int)sub_1669() == 2 )
  {
    v0 = (_QWORD *)operator new(0x1CuLL);
    sub_116E(v0);
    puts("Choose color:\n\t1. Black\n\t2. White");
    v1 = sub_1669();
    sub_12C0((__int64)v0, v1);
    printf("Enter pet name:");
    fgets(s, 256, _bss_start);
    v4 = strchr(s, 10);
    if ( v4 )
      *v4 = 0;
    sub_1E10((__int64)v0, s);
    v2 = dword_2030D0++;
    qword_203080[v2] = v0;
    printf("your new pet has number %d\n", dword_2030D0);
  }
  else
  {
    puts("The pet has now sold out.");
  }
  return __readfsqword(0x28u) ^ v6;
}
// 1669: using guessed type __int64 sub_1669(void);
// 203080: using guessed type _QWORD qword_203080[10];
// 2030D0: using guessed type int dword_2030D0;

//----- (00000000000018C0) ----------------------------------------------------
int sub_18C0()
{
  unsigned int v1; // [rsp+8h] [rbp-8h]
  __int16 v2; // [rsp+Ch] [rbp-4h]

  printf("Enter pet number:");
  v1 = sub_1669() - 1;
  if ( v1 > 9 || !qword_203080[v1] )
    return puts("Invalid pet number");
  printf("How many cups of food? ");
  v2 = sub_1669();
  return sub_1E70(qword_203080[v1], v2);
}
// 1669: using guessed type __int64 sub_1669(void);
// 203080: using guessed type _QWORD qword_203080[10];

//----- (000000000000195C) ----------------------------------------------------
int sub_195C()
{
  unsigned int v1; // [rsp+Ch] [rbp-4h]

  printf("Enter pet number:");
  v1 = sub_1669() - 1;
  if ( v1 <= 9 && qword_203080[v1] )
    return sub_1E9A(qword_203080[v1]);
  else
    return puts("Invalid pet number");
}
// 1669: using guessed type __int64 sub_1669(void);
// 203080: using guessed type _QWORD qword_203080[10];

//----- (00000000000019DA) ----------------------------------------------------
int sub_19DA()
{
  unsigned int i; // [rsp+Ch] [rbp-4h]

  printf("Number of your pets: %d\n", dword_2030D0);
  for ( i = 0; i < dword_2030D0; ++i )
    sub_151F(qword_203080[i]);
  return putchar(10);
}
// 203080: using guessed type _QWORD qword_203080[10];
// 2030D0: using guessed type int dword_2030D0;

//----- (0000000000001A3E) ----------------------------------------------------
unsigned __int64 sub_1A3E()
{
  int v0; // eax
  unsigned int v2; // [rsp+4h] [rbp-12Ch]
  __int64 v3; // [rsp+8h] [rbp-128h]
  char *v4; // [rsp+10h] [rbp-120h]
  char *v5; // [rsp+18h] [rbp-118h]
  char s[264]; // [rsp+20h] [rbp-110h] BYREF
  unsigned __int64 v7; // [rsp+128h] [rbp-8h]

  v7 = __readfsqword(0x28u);
  printf("Enter pet number:");
  v2 = sub_1669() - 1;
  if ( v2 <= 9 && qword_203080[v2] )
  {
    v3 = qword_203080[v2];
    v0 = sub_1DFA(v3);
    switch ( v0 )
    {
      case 2:
        puts("Meow!!miaow!");
        break;
      case 3:
        printf("Train your fish?(Y/N) ");
        fgets(s, 256, _bss_start);
        if ( s[0] == 89 || s[0] == 121 )
        {
          sub_15C3(v3);
        }
        else
        {
          printf("Enter area:");
          fgets(s, 256, _bss_start);
          v5 = strchr(s, 10);
          if ( v5 )
            *v5 = 0;
          sub_113C(v3, (__int64)s);
        }
        break;
      case 1:
        printf("Change color?(Y/N) ");
        fgets(s, 256, _bss_start);
        if ( s[0] == 89 || s[0] == 121 )
        {
          printf("New color: ");
          fgets(s, 256, _bss_start);
          v4 = strchr(s, 10);
          if ( v4 )
            *v4 = 0;
          sub_14E3(v3, (unsigned __int8 *)s);
        }
        puts("Bark!!Bark!");
        break;
    }
  }
  else
  {
    puts("Invalid pet number");
  }
  return __readfsqword(0x28u) ^ v7;
}
// 1669: using guessed type __int64 sub_1669(void);
// 203080: using guessed type _QWORD qword_203080[10];

//----- (0000000000001CC5) ----------------------------------------------------
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3)
{
  sub_1604(a1, a2, a3);
  while ( 1 )
  {
    switch ( (unsigned int)sub_16AD() )
    {
      case 1u:
        sub_1729();
        break;
      case 2u:
        sub_18C0();
        break;
      case 3u:
        sub_195C();
        break;
      case 4u:
        sub_19DA();
        break;
      case 5u:
        sub_1A3E();
        break;
      case 6u:
        exit(0);
      default:
        continue;
    }
  }
}
// 1604: using guessed type __int64 __fastcall sub_1604(_QWORD, _QWORD, _QWORD);
// 16AD: using guessed type __int64 sub_16AD(void);
// 1729: using guessed type __int64 sub_1729(void);
// 18C0: using guessed type __int64 sub_18C0(void);
// 195C: using guessed type __int64 sub_195C(void);
// 19DA: using guessed type __int64 sub_19DA(void);
// 1A3E: using guessed type __int64 sub_1A3E(void);

//----- (0000000000001D36) ----------------------------------------------------
__int64 __fastcall sub_1D36(__int64 a1)
{
  __int64 result; // rax

  *(_QWORD *)a1 = off_202CD0;
  *(_QWORD *)(a1 + 10) = 0LL;
  *(_BYTE *)(a1 + 9) = 0;
  result = a1;
  *(_BYTE *)(a1 + 8) = 0;
  return result;
}
// 202CD0: using guessed type __int64 (__fastcall *off_202CD0[2])();

//----- (0000000000001D6C) ----------------------------------------------------
__int64 __fastcall sub_1D6C(__int64 a1)
{
  *(_QWORD *)a1 = off_202CD0;
  if ( !*(_QWORD *)(a1 + 10) )
    free(*(void **)(a1 + 10));
  return 0LL;
}
// 202CD0: using guessed type __int64 (__fastcall *off_202CD0[2])();

//----- (0000000000001DBA) ----------------------------------------------------
void __fastcall sub_1DBA(void *a1)
{
  sub_1D6C((__int64)a1);
  operator delete(a1);
}

//----- (0000000000001DE0) ----------------------------------------------------
__int64 __fastcall sub_1DE0(__int64 a1, char a2)
{
  __int64 result; // rax

  result = a1;
  *(_BYTE *)(a1 + 9) = a2;
  return result;
}

//----- (0000000000001DFA) ----------------------------------------------------
__int64 __fastcall sub_1DFA(__int64 a1)
{
  return (unsigned int)*(char *)(a1 + 9);
}

//----- (0000000000001E10) ----------------------------------------------------
void __fastcall sub_1E10(__int64 a1, const char *a2)
{
  if ( !*(_QWORD *)(a1 + 10) )
    free(*(void **)(a1 + 10));
  if ( a2 )
    *(_QWORD *)(a1 + 10) = strdup(a2);
}

//----- (0000000000001E5E) ----------------------------------------------------
__int64 __fastcall sub_1E5E(__int64 a1)
{
  return *(_QWORD *)(a1 + 10);
}

//----- (0000000000001E70) ----------------------------------------------------
__int64 __fastcall sub_1E70(__int64 a1, __int16 a2)
{
  __int64 result; // rax

  result = a1 + 8;
  *(_WORD *)(a1 + 8) += a2;
  return result;
}

//----- (0000000000001E9A) ----------------------------------------------------
__int64 __fastcall sub_1E9A(__int64 a1)
{
  int v1; // ecx
  __int64 result; // rax

  v1 = rand() % 5;
  result = a1 + 8;
  *(_WORD *)(a1 + 8) -= v1;
  return result;
}

//----- (0000000000001EE8) ----------------------------------------------------
__int64 __fastcall sub_1EE8(__int64 a1)
{
  return *(unsigned __int8 *)(a1 + 8);
}

//----- (0000000000001EFE) ----------------------------------------------------
int __fastcall sub_1EFE(__int64 a1, char a2)
{
  if ( a2 )
    puts("Type\tName\t\tCups");
  return printf(
           "%s\t%s\t\t%d\n",
           (const char *)*(&off_203020 + *(char *)(a1 + 9)),
           *(const char **)(a1 + 10),
           *(unsigned __int8 *)(a1 + 8));
}
// 203020: using guessed type _UNKNOWN *off_203020;

//----- (0000000000001F70) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  v4 = &off_202C50 - off_202C48;
  init_proc();
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_202C48[i])(a1, a2, a3);
  }
}
// 202C48: using guessed type __int64 (__fastcall *off_202C48[2])();
// 202C50: using guessed type __int64 (__fastcall *off_202C50)();

//----- (0000000000001FE4) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=93 queued=48 decompiled=48 lumina nreq=0 worse=0 better=0
// ALL OK, 48 function(s) have been successfully decompiled
